// <auto-generated />
using System;
using EntityFrameWork02.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameWork02.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221122101124_Seeding Language")]
    partial class SeedingLanguage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CityCountry", b =>
                {
                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CityName", "CountryName");

                    b.HasIndex("CountryName");

                    b.ToTable("CityCountry");
                });

            modelBuilder.Entity("CityPerson", b =>
                {
                    b.Property<string>("CitysName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PeopleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CitysName", "PeopleId");

                    b.HasIndex("PeopleId");

                    b.ToTable("CityPerson");
                });

            modelBuilder.Entity("CountryPerson", b =>
                {
                    b.Property<string>("CountrysName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PersonId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CountrysName", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("CountryPerson");
                });

            modelBuilder.Entity("EntityFrameWork02.Models.City", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Register")
                        .HasColumnType("datetime2");

                    b.HasKey("Name");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            Name = "Åre",
                            PostNumber = "123 45",
                            Register = new DateTime(2022, 11, 22, 11, 11, 23, 749, DateTimeKind.Local).AddTicks(2315)
                        },
                        new
                        {
                            Name = "Järpen",
                            PostNumber = "123 45",
                            Register = new DateTime(2022, 11, 22, 11, 11, 23, 749, DateTimeKind.Local).AddTicks(2329)
                        },
                        new
                        {
                            Name = "Östersund",
                            PostNumber = "123 88",
                            Register = new DateTime(2022, 11, 22, 11, 11, 23, 749, DateTimeKind.Local).AddTicks(2338)
                        });
                });

            modelBuilder.Entity("EntityFrameWork02.Models.Country", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Register")
                        .HasColumnType("datetime2");

                    b.HasKey("Name");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Name = "Sweden",
                            Register = new DateTime(2022, 11, 22, 11, 11, 23, 749, DateTimeKind.Local).AddTicks(2354)
                        },
                        new
                        {
                            Name = "Norway",
                            Register = new DateTime(2022, 11, 22, 11, 11, 23, 749, DateTimeKind.Local).AddTicks(2367)
                        },
                        new
                        {
                            Name = "Danmark",
                            Register = new DateTime(2022, 11, 22, 11, 11, 23, 749, DateTimeKind.Local).AddTicks(2415)
                        });
                });

            modelBuilder.Entity("EntityFrameWork02.Models.Language", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Language");

                    b.HasData(
                        new
                        {
                            Name = "Svenska"
                        },
                        new
                        {
                            Name = "Norske"
                        },
                        new
                        {
                            Name = "Periska"
                        });
                });

            modelBuilder.Entity("EntityFrameWork02.Models.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("EfterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Register")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = "cb9cb5a4-ce7b-49c0-b60d-b0a5fee79750",
                            Age = 32,
                            EfterName = "Khokho",
                            Name = "Ali",
                            PhoneNumer = "123456",
                            Register = new DateTime(2022, 11, 22, 11, 11, 23, 749, DateTimeKind.Local).AddTicks(2209)
                        },
                        new
                        {
                            Id = "b514fd11-e586-47cf-9beb-d821a39f8b6d",
                            Age = 23,
                            EfterName = "klhpioj",
                            Name = "Ali01",
                            PhoneNumer = "123546",
                            Register = new DateTime(2022, 11, 22, 11, 11, 23, 749, DateTimeKind.Local).AddTicks(2276)
                        },
                        new
                        {
                            Id = "38d71696-a732-4296-bb45-b49c72b1acb1",
                            Age = 23,
                            EfterName = "klhpioj",
                            Name = "Ali02",
                            PhoneNumer = "123546",
                            Register = new DateTime(2022, 11, 22, 11, 11, 23, 749, DateTimeKind.Local).AddTicks(2289)
                        },
                        new
                        {
                            Id = "43725d4f-4066-45be-9399-91b2fb0fcd27",
                            Age = 23,
                            EfterName = "klhpioj",
                            Name = "Ali03",
                            PhoneNumer = "123546",
                            Register = new DateTime(2022, 11, 22, 11, 11, 23, 749, DateTimeKind.Local).AddTicks(2300)
                        });
                });

            modelBuilder.Entity("CityCountry", b =>
                {
                    b.HasOne("EntityFrameWork02.Models.City", null)
                        .WithMany()
                        .HasForeignKey("CityName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFrameWork02.Models.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CityPerson", b =>
                {
                    b.HasOne("EntityFrameWork02.Models.City", null)
                        .WithMany()
                        .HasForeignKey("CitysName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFrameWork02.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("PeopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CountryPerson", b =>
                {
                    b.HasOne("EntityFrameWork02.Models.Country", null)
                        .WithMany()
                        .HasForeignKey("CountrysName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFrameWork02.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
