// <auto-generated />
using System;
using EntityFrameWork02.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameWork02.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221122090138_Seeding Data")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EntityFrameWork02.Models.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("EfterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Register")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = "cacac3c8-520b-46bc-88d0-eafa6a6029e4",
                            Age = 32,
                            EfterName = "Khokho",
                            Name = "Ali",
                            PhoneNumer = "123456",
                            Register = new DateTime(2022, 11, 22, 10, 1, 38, 241, DateTimeKind.Local).AddTicks(9654)
                        },
                        new
                        {
                            Id = "986c95ba-dc2c-441f-b1a5-52e3467efec9",
                            Age = 23,
                            EfterName = "klhpioj",
                            Name = "Ali01",
                            PhoneNumer = "123546",
                            Register = new DateTime(2022, 11, 22, 10, 1, 38, 241, DateTimeKind.Local).AddTicks(9712)
                        },
                        new
                        {
                            Id = "ba235338-8ba3-485b-bfbf-838c6e56ffee",
                            Age = 23,
                            EfterName = "klhpioj",
                            Name = "Ali02",
                            PhoneNumer = "123546",
                            Register = new DateTime(2022, 11, 22, 10, 1, 38, 241, DateTimeKind.Local).AddTicks(9737)
                        },
                        new
                        {
                            Id = "3e623a9d-8fb9-44d1-b2ae-90a5efc6a961",
                            Age = 23,
                            EfterName = "klhpioj",
                            Name = "Ali03",
                            PhoneNumer = "123546",
                            Register = new DateTime(2022, 11, 22, 10, 1, 38, 241, DateTimeKind.Local).AddTicks(9748)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
